logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: python_logs
        static_configs:
          - targets: [localhost]
            labels:
              app: python_app
              __path__: [APP_LOG_PATH]
    clients:
      - url: [LOGS_WRITE_CONFIG_COPY_PASTE]
metrics:
  global:
    [REMOTE_WRITE_CONFIG_COPY_PASTE]
    scrape_interval: 60s
    external_labels:
      app: python_app
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: python_node
        static_configs:
        - targets: ['localhost:8080']
integrations:
  node_exporter:
    enabled: true
  agent:
    enabled: true