metrics:
  global:
    [REMOTE_WRITE_CONFIG_COPY_PASTE]
    scrape_interval: 60s
    external_labels:
      app: python_app
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: python_node
        static_configs:
        - targets: ['localhost:8080']
integrations:
  node_exporter:
    enabled: true
  agent:
    enabled: true